### PR TITLE
Restructurize repo to stay clean und clear

### PR DESCRIPTION
**Pull request by BjoernLudwigPTB**
This restructurizes the code to clean up root folder whilst keeping or even improving meaningful imports. It is of course only a proposal and I am totally fine with other suggestions or the current state. In that case though, we should still cherry-pick the [first couple of commits](https://github.com/bangxiangyong/agentMet4FoF/pull/13/files/b8aaeee1c57239d8cfc1c071bda58923493755ba..47c124edc70c8c23f26dc8a3e654f754de766c71) to increase testing rate of the important bits.

The essence of what we did was inserting a folder _agentMet4FoF_ with the name of the actual _product_ and move all production code files into that subfolder or into according subfolders of it. We ended up with a structure like:
```
root/
|-> agentMET4FOF/
|   |-> dashboard/
|   |   |-> assets/
|   |   |-> Dashboard.py
|   |   |-> Dashboard_Control.py
|   |   |-> Layout_Helper.py
|   |-> develop/
|   |-> agents.py
|   |-> streams.py
|   |-> ...
|-> docs/
|-> examples/
|-> tests/
|-> tutorials/
|-> README.md
|-> ...
```
which allows for imports like:

``` python
from agentMET4FOF.agents import AgentMET4FOF, AgentNetwork, MonitorAgent
from agentMET4FOF.streams import SineGenerator

import agentMET4FOF.agents as agentmet4fof_module
import agentMET4FOF.streams as datastreammet4fof_module
```
Look [here](https://github.com/bangxiangyong/agentMet4FoF/tree/restructurize) for the current state of the file and folder structure.

### CODE REVIEW

**Comment by BjoernLudwigPTB** [comment]
> 
> # [Codecov](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13?src=pr&el=h1) Report
> 
> > Merging [#13](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13?src=pr&el=desc) into [master](https://codecov.io/gh/bangxiangyong/agentMet4FoF/commit/691771ce05987c31bf8a78f145511a1856e9d24f?src=pr&el=desc) will **decrease** coverage by `12.47%`.
> > The diff coverage is `73.52%`.
> 
> [Impacted file tree graph](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13?src=pr&el=tree)
> 
> ```diff
> @@             Coverage Diff             @@
> ##           master      #13       +/-   ##
> ===========================================
> - Coverage   55.85%   43.38%   -12.48%     
> ===========================================
>   Files           4       18       +14     
>   Lines         512     1376      +864     
>   Branches       91      198      +107     
> ===========================================
> + Hits          286      597      +311     
> - Misses        194      741      +547     
> - Partials       32       38        +6
> ```
> 
> [Impacted Files](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13?src=pr&el=tree) 	Coverage Δ 	
> [examples/ZEMA_EMC/zema_datastream.py](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13/diff?src=pr&el=tree#diff-ZXhhbXBsZXMvWkVNQV9FTUMvemVtYV9kYXRhc3RyZWFtLnB5) 	`22.95% <0%> (ø)` 	
> [tutorials/tutorial_3_multi_channel.py](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13/diff?src=pr&el=tree#diff-dHV0b3JpYWxzL3R1dG9yaWFsXzNfbXVsdGlfY2hhbm5lbC5weQ==) 	`64.86% <100%> (ø)` 	
> [examples/ML/coupled_ML.py](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13/diff?src=pr&el=tree#diff-ZXhhbXBsZXMvTUwvY291cGxlZF9NTC5weQ==) 	`53.57% <100%> (ø)` 	
> [examples/demo/demo_agent_network.py](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13/diff?src=pr&el=tree#diff-ZXhhbXBsZXMvZGVtby9kZW1vX2FnZW50X25ldHdvcmsucHk=) 	`100% <100%> (ø)` 	
> [examples/demo/demo_agents.py](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13/diff?src=pr&el=tree#diff-ZXhhbXBsZXMvZGVtby9kZW1vX2FnZW50cy5weQ==) 	`76.92% <100%> (ø)` 	
> [tutorials/tutorial_2_math_agent.py](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13/diff?src=pr&el=tree#diff-dHV0b3JpYWxzL3R1dG9yaWFsXzJfbWF0aF9hZ2VudC5weQ==) 	`72.5% <100%> (ø)` 	
> [examples/ML/decoupled_ML.py](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13/diff?src=pr&el=tree#diff-ZXhhbXBsZXMvTUwvZGVjb3VwbGVkX01MLnB5) 	`57.62% <100%> (ø)` 	
> [tutorials/tutorial_1_generator_agent.py](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13/diff?src=pr&el=tree#diff-dHV0b3JpYWxzL3R1dG9yaWFsXzFfZ2VuZXJhdG9yX2FnZW50LnB5) 	`82.35% <100%> (ø)` 	
> [examples/ZEMA_EMC/main_zema_agents.py](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13/diff?src=pr&el=tree#diff-ZXhhbXBsZXMvWkVNQV9FTUMvbWFpbl96ZW1hX2FnZW50cy5weQ==) 	`19.44% <11.11%> (ø)` 	
> ... and [15 more](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13/diff?src=pr&el=tree-more) 		
> 
> [Continue to review full report at Codecov](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13?src=pr&el=continue).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13?src=pr&el=footer). Last update [691771c...0c96171](https://codecov.io/gh/bangxiangyong/agentMet4FoF/pull/13?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

That's hard to compare, because this includes much more fiels into the report. Especially the very important tutorials and examples are now tested excluding the ZeMA stuff because of the huge amount of data needed for the tests.

**Comment by bangxiangyong** [comment]
Looks good and much neater!

Have two concerns :
1) Due to the irregular higher and lowercase, `agentMet4FoF` as the base may be a little unnatural to type and especially for those without intellisense. May I suggest agentMET4FOF instead or some other names? 

2) It appears that the testing bits revolved around checking if the agents are able to shutdown, I am not sure if that's the best way because i think the agents will still be able to shutdown despite facing an error.

**Comment by BjoernLudwigPTB** [comment]
> 1. Due to the irregular higher and lowercase, `agentMet4FoF` as the base may be a little unnatural to type and especially for those without intellisense. May I suggest `agentMET4FOF` instead or some other names?

Of course I can change that. I chose the name of the repository. Shall we keep things consistent and change the repo name as well? GitHub will then create redirects, so old links will all still work. And just to be clear: you mean the name of the freshly created folder, do you?

> 2. It appears that the testing bits revolved around checking if the agents are able to shutdown, I am not sure if that's the best way because i think the agents will still be able to shutdown despite facing an error.

I think this is a misunderstanding. Before I wrote those new tests, I extracted all contents of the `if __name__ = "__main__"` portions of the examples and tutorials into a method `main()` and execute that in the tests. The shutdown statement in the test itself just makes sure, that the execution actually terminates. It executes the whole code in `main()`, gets the created agent network as return value and then shuts down the network. Basically what I wrote is a shorter way of:
```
agent_network = main()
agent_network.shutdown()
```

**Comment by bangxiangyong** [comment]
1. Yes I meant the freshly created folder which I see you've renamed it :)

2. I understand what you did on main() and shutdown(), but what I meant was the essence of testing. Because effectively now the tests for tutorials are going to pass most of the time, as long as the base functions and agents are able to be initiated (via .add_agent()) and bind (via .bind_agents()). 

I was thinking of asserting on the agent's individual attributes to check the logic for each tutorial's purposes e.g in tutorial 2 would be on the math agent's expected outputs and tutorial 3 would be on testing the multi-channel's functionalities.

**Comment by BjoernLudwigPTB** [comment]
> 2. I understand what you did on main() and shutdown(), but what I meant was the essence of testing. Because effectively now the tests for tutorials are going to pass most of the time, as long as the base functions and agents are able to be initiated (via .add_agent()) and bind (via .bind_agents()). I was thinking of asserting on the agent's individual attributes to check the logic for each tutorial's purposes e.g in tutorial 2 would be on the math agent's expected outputs and tutorial 3 would be on testing the multi-channel's functionalities.

I see! My idea was in fact as simple as you describe it. The tests you describe are diserable from my point of view as well. What about setting up the structure as a first step and then enhancing it with more meaningful tests as a second step. Which means opening an issue at the same time?

**Comment by bangxiangyong** [comment]
No worries at all, it's good to be clear and appreciate the effort.. Yes, i'll add it in next days

**Comment by BjoernLudwigPTB** [comment]
> No worries at all, it's good to be clear and appreciate the effort.. Yes, i'll add it in next days

Perfect! Maybe we can think of a way to avoid duplication of the code by returning not only the network or maybe accessing the properties to be tested via the already returned network?

**Comment by bangxiangyong** [comment]
Yes ... that's one of the challenges here .. ! I think i know how to go around it now that you mentioned that we've got the returned network already..

**Comment by BjoernLudwigPTB** [comment]
This merge really got me quite excited. ;) What about the repo namestick to _agentMet4FoF_ or rather rename it to _agentMET4FOF_. Old links [will still work ](https://help.github.com/en/articles/renaming-a-repository. It just contributes to consistency and clearness, I suppose.

**Comment by bangxiangyong** [comment]
Good to know that, thanks for the contribution! yes i think renaming to agentMET4FOF makes sense..

**Comment by BjoernLudwigPTB** [comment]
> Good to know that, thanks for the contribution! yes i think renaming to agentMET4FOF makes sense..

You find the according setting [here](https://github.com/bangxiangyong/agentMet4FoF/settings).

**Pull request merged**
